package sproutling;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

public final class EventOuterClass {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Event_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Event_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\013event.proto\032\037google/protobuf/timestamp" +
                        ".proto\"\302\001\n\005Event\022-\n\ttimestamp\030\001 \001(\0132\032.go" +
                        "ogle.protobuf.Timestamp\022\016\n\006serial\030\002 \001(\t\022" +
                        "\020\n\010child_id\030\003 \001(\t\022\031\n\005event\030\004 \001(\0162\n.Event" +
                        "Type\022\024\n\nheart_rate\030\005 \001(\rH\000\022\034\n\022battery_pe" +
                        "rcentage\030\006 \001(\rH\000\022\020\n\010swstatus\030\007 \001(\tB\007\n\005ex" +
                        "tra*\370\002\n\tEventType\022\013\n\007UNKNOWN\020\000\022\023\n\017LEARNI" +
                        "NG_PERIOD\020\001\022\t\n\005AWAKE\020\002\022\014\n\010STIRRING\020\003\022\n\n\006" +
                        "ASLEEP\020\004\022\016\n\nHEART_RATE\020\005\022\026\n\022HEART_RATE_U" +
                        "NUSUAL\020\006\022\017\n\013ROLLED_OVER\020\007\022\022\n\016WEARABLE_RE",
                "ADY\020\010\022\024\n\020WEARABLE_BATTERY\020\t\022\025\n\021WEARABLE_" +
                        "CHARGING\020\n\022\024\n\020WEARABLE_CHARGED\020\013\022\031\n\025WEAR" +
                        "ABLE_TOO_FAR_AWAY\020\014\022\026\n\022WEARABLE_NOT_FOUN" +
                        "D\020\r\022\025\n\021WEARABLE_FELL_OFF\020\016\022\017\n\013HUB_OFFLIN" +
                        "E\020\017\022\016\n\nNO_SERVICE\020\020\022\016\n\nHUB_ONLINE\020\021\022\031\n\025W" +
                        "EARABLE_BATTERY_DEAD\020\022B#Z!github.com/Mat" +
                        "tel/protocol;protosb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.google.protobuf.TimestampProto.getDescriptor(),
                        }, assigner);
        internal_static_Event_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_Event_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Event_descriptor,
                new String[]{"Timestamp", "Serial", "ChildId", "Event", "HeartRate", "BatteryPercentage", "Swstatus", "Extra",});
        com.google.protobuf.TimestampProto.getDescriptor();
    }

  private EventOuterClass() {}

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

  /**
   * Protobuf enum {@code EventType}
   */
  public enum EventType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <pre>
     * Status
     * </pre>
     *
     * <code>LEARNING_PERIOD = 1;</code>
     */
    LEARNING_PERIOD(1),
    /**
     * <pre>
     * Status
     * </pre>
     *
     * <code>AWAKE = 2;</code>
     */
    AWAKE(2),
    /**
     * <pre>
     * Status
     * </pre>
     *
     * <code>STIRRING = 3;</code>
     */
    STIRRING(3),
    /**
     * <pre>
     * Status
     * </pre>
     *
     * <code>ASLEEP = 4;</code>
     */
    ASLEEP(4),
    /**
     * <pre>
     * n/a
     * </pre>
     *
     * <code>HEART_RATE = 5;</code>
     */
    HEART_RATE(5),
    /**
     * <pre>
     * Alert
     * </pre>
     *
     * <code>HEART_RATE_UNUSUAL = 6;</code>
     */
    HEART_RATE_UNUSUAL(6),
    /**
     * <pre>
     * Alert
     * </pre>
     *
     * <code>ROLLED_OVER = 7;</code>
     */
    ROLLED_OVER(7),
    /**
     * <pre>
     * Status
     * </pre>
     *
     * <code>WEARABLE_READY = 8;</code>
     */
    WEARABLE_READY(8),
    /**
     * <pre>
     * Alert
     * </pre>
     *
     * <code>WEARABLE_BATTERY = 9;</code>
     */
    WEARABLE_BATTERY(9),
    /**
     * <pre>
     * Status
     * </pre>
     *
     * <code>WEARABLE_CHARGING = 10;</code>
     */
    WEARABLE_CHARGING(10),
    /**
     * <pre>
     * Status
     * </pre>
     *
     * <code>WEARABLE_CHARGED = 11;</code>
     */
    WEARABLE_CHARGED(11),
    /**
     * <pre>
     * Status
     * </pre>
     *
     * <code>WEARABLE_TOO_FAR_AWAY = 12;</code>
     */
    WEARABLE_TOO_FAR_AWAY(12),
    /**
     * <pre>
     * Satus
     * </pre>
     *
     * <code>WEARABLE_NOT_FOUND = 13;</code>
     */
    WEARABLE_NOT_FOUND(13),
    /**
     * <pre>
     * Status
     * </pre>
     *
     * <code>WEARABLE_FELL_OFF = 14;</code>
     */
    WEARABLE_FELL_OFF(14),
    /**
     * <pre>
     * Status
     * </pre>
     *
     * <code>HUB_OFFLINE = 15;</code>
     */
    HUB_OFFLINE(15),
    /**
     * <pre>
     * n/a
     * </pre>
     *
     * <code>NO_SERVICE = 16;</code>
     */
    NO_SERVICE(16),
    /**
     * <pre>
     * Status
     * </pre>
     *
     * <code>HUB_ONLINE = 17;</code>
     */
    HUB_ONLINE(17),
    /**
     * <pre>
     * Status
     * </pre>
     *
     * <code>WEARABLE_BATTERY_DEAD = 18;</code>
     */
    WEARABLE_BATTERY_DEAD(18),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * Status
     * </pre>
     *
     * <code>LEARNING_PERIOD = 1;</code>
     */
    public static final int LEARNING_PERIOD_VALUE = 1;
    /**
     * <pre>
     * Status
     * </pre>
     *
     * <code>AWAKE = 2;</code>
     */
    public static final int AWAKE_VALUE = 2;
    /**
     * <pre>
     * Status
     * </pre>
     *
     * <code>STIRRING = 3;</code>
     */
    public static final int STIRRING_VALUE = 3;
    /**
     * <pre>
     * Status
     * </pre>
     *
     * <code>ASLEEP = 4;</code>
     */
    public static final int ASLEEP_VALUE = 4;
    /**
     * <pre>
     * n/a
     * </pre>
     *
     * <code>HEART_RATE = 5;</code>
     */
    public static final int HEART_RATE_VALUE = 5;
    /**
     * <pre>
     * Alert
     * </pre>
     *
     * <code>HEART_RATE_UNUSUAL = 6;</code>
     */
    public static final int HEART_RATE_UNUSUAL_VALUE = 6;
    /**
     * <pre>
     * Alert
     * </pre>
     *
     * <code>ROLLED_OVER = 7;</code>
     */
    public static final int ROLLED_OVER_VALUE = 7;
    /**
     * <pre>
     * Status
     * </pre>
     *
     * <code>WEARABLE_READY = 8;</code>
     */
    public static final int WEARABLE_READY_VALUE = 8;
    /**
     * <pre>
     * Alert
     * </pre>
     *
     * <code>WEARABLE_BATTERY = 9;</code>
     */
    public static final int WEARABLE_BATTERY_VALUE = 9;
    /**
     * <pre>
     * Status
     * </pre>
     *
     * <code>WEARABLE_CHARGING = 10;</code>
     */
    public static final int WEARABLE_CHARGING_VALUE = 10;
    /**
     * <pre>
     * Status
     * </pre>
     *
     * <code>WEARABLE_CHARGED = 11;</code>
     */
    public static final int WEARABLE_CHARGED_VALUE = 11;
    /**
     * <pre>
     * Status
     * </pre>
     *
     * <code>WEARABLE_TOO_FAR_AWAY = 12;</code>
     */
    public static final int WEARABLE_TOO_FAR_AWAY_VALUE = 12;
    /**
     * <pre>
     * Satus
     * </pre>
     *
     * <code>WEARABLE_NOT_FOUND = 13;</code>
     */
    public static final int WEARABLE_NOT_FOUND_VALUE = 13;
    /**
     * <pre>
     * Status
     * </pre>
     *
     * <code>WEARABLE_FELL_OFF = 14;</code>
     */
    public static final int WEARABLE_FELL_OFF_VALUE = 14;
    /**
     * <pre>
     * Status
     * </pre>
     *
     * <code>HUB_OFFLINE = 15;</code>
     */
    public static final int HUB_OFFLINE_VALUE = 15;
    /**
     * <pre>
     * n/a
     * </pre>
     *
     * <code>NO_SERVICE = 16;</code>
     */
    public static final int NO_SERVICE_VALUE = 16;
    /**
     * <pre>
     * Status
     * </pre>
     *
     * <code>HUB_ONLINE = 17;</code>
     */
    public static final int HUB_ONLINE_VALUE = 17;
    /**
     * <pre>
     * Status
     * </pre>
     *
     * <code>WEARABLE_BATTERY_DEAD = 18;</code>
     */
    public static final int WEARABLE_BATTERY_DEAD_VALUE = 18;
      private static final com.google.protobuf.Internal.EnumLiteMap<
              EventType> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
                  public EventType findValueByNumber(int number) {
                      return EventType.forNumber(number);
                  }
              };
      private static final EventType[] VALUES = values();
      private final int value;

      private EventType(int value) {
          this.value = value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static EventType valueOf(int value) {
      return forNumber(value);
    }

    public static EventType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return LEARNING_PERIOD;
        case 2: return AWAKE;
        case 3: return STIRRING;
        case 4: return ASLEEP;
        case 5: return HEART_RATE;
        case 6: return HEART_RATE_UNUSUAL;
        case 7: return ROLLED_OVER;
        case 8: return WEARABLE_READY;
        case 9: return WEARABLE_BATTERY;
        case 10: return WEARABLE_CHARGING;
        case 11: return WEARABLE_CHARGED;
        case 12: return WEARABLE_TOO_FAR_AWAY;
        case 13: return WEARABLE_NOT_FOUND;
        case 14: return WEARABLE_FELL_OFF;
        case 15: return HUB_OFFLINE;
        case 16: return NO_SERVICE;
        case 17: return HUB_ONLINE;
        case 18: return WEARABLE_BATTERY_DEAD;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EventType>
        internalGetValueMap() {
      return internalValueMap;
    }

    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return EventOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    public static EventType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

      public final int getNumber() {
          if (this == UNRECOGNIZED) {
              throw new IllegalArgumentException(
                      "Can't get the number of an unknown enum value.");
          }
          return value;
      }

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
          return getDescriptor().getValues().get(ordinal());
      }

      public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
          return getDescriptor();
    }

    // @@protoc_insertion_point(enum_scope:EventType)
  }
  public interface EventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Event)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Timestamp
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp timestamp = 1;</code>
     */
    boolean hasTimestamp();
    /**
     * <pre>
     * Timestamp
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp timestamp = 1;</code>
     */
    com.google.protobuf.Timestamp getTimestamp();
    /**
     * <pre>
     * Timestamp
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp timestamp = 1;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

    /**
     * <pre>
     * Hub serial number
     * </pre>
     *
     * <code>optional string serial = 2;</code>
     */
    String getSerial();
    /**
     * <pre>
     * Hub serial number
     * </pre>
     *
     * <code>optional string serial = 2;</code>
     */
    com.google.protobuf.ByteString
        getSerialBytes();

    /**
     * <pre>
     * Child ID
     * </pre>
     *
     * <code>optional string child_id = 3;</code>
     */
    String getChildId();
    /**
     * <pre>
     * Child ID
     * </pre>
     *
     * <code>optional string child_id = 3;</code>
     */
    com.google.protobuf.ByteString
        getChildIdBytes();

    /**
     * <pre>
     * Event type
     * </pre>
     *
     * <code>optional .EventType event = 4;</code>
     */
    int getEventValue();
    /**
     * <pre>
     * Event type
     * </pre>
     *
     * <code>optional .EventType event = 4;</code>
     */
    EventType getEvent();

    /**
     * <pre>
     * Heart rate in BPM
     * </pre>
     *
     * <code>optional uint32 heart_rate = 5;</code>
     */
    int getHeartRate();

    /**
     * <pre>
     * Battery percentage
     * </pre>
     *
     * <code>optional uint32 battery_percentage = 6;</code>
     */
    int getBatteryPercentage();

    /**
     * <code>optional string swstatus = 7;</code>
     */
    String getSwstatus();
    /**
     * <code>optional string swstatus = 7;</code>
     */
    com.google.protobuf.ByteString
        getSwstatusBytes();

      public Event.ExtraCase getExtraCase();
  }

  /**
   * <pre>
   * Event [device/hub/SN_HUB/events]
   *    Event report.
   * </pre>
   *
   * Protobuf type {@code Event}
   */
  public  static final class Event extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Event)
      EventOrBuilder {
      public static final int TIMESTAMP_FIELD_NUMBER = 1;
      public static final int SERIAL_FIELD_NUMBER = 2;
      public static final int CHILD_ID_FIELD_NUMBER = 3;
      public static final int EVENT_FIELD_NUMBER = 4;
      public static final int HEART_RATE_FIELD_NUMBER = 5;
      public static final int BATTERY_PERCENTAGE_FIELD_NUMBER = 6;
      public static final int SWSTATUS_FIELD_NUMBER = 7;
      private static final long serialVersionUID = 0L;
      // @@protoc_insertion_point(class_scope:Event)
      private static final Event DEFAULT_INSTANCE;
      ;
      private static final com.google.protobuf.Parser<Event>
              PARSER = new com.google.protobuf.AbstractParser<Event>() {
          public Event parsePartialFrom(
                  com.google.protobuf.CodedInputStream input,
                  com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                  throws com.google.protobuf.InvalidProtocolBufferException {
              return new Event(input, extensionRegistry);
          }
      };

      static {
          DEFAULT_INSTANCE = new Event();
      }

      private int extraCase_ = 0;
      private Object extra_;
      private com.google.protobuf.Timestamp timestamp_;
      private volatile Object serial_;
      private volatile Object childId_;
      private int event_;
      private volatile Object swstatus_;
      private byte memoizedIsInitialized = -1;

    // Use Event.newBuilder() to construct.
    private Event(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Event() {
      serial_ = "";
      childId_ = "";
      event_ = 0;
      swstatus_ = "";
    }
    private Event(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (timestamp_ != null) {
                subBuilder = timestamp_.toBuilder();
              }
              timestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(timestamp_);
                timestamp_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
                String s = input.readStringRequireUtf8();

              serial_ = s;
              break;
            }
            case 26: {
                String s = input.readStringRequireUtf8();

              childId_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              event_ = rawValue;
              break;
            }
            case 40: {
              extraCase_ = 5;
              extra_ = input.readUInt32();
              break;
            }
            case 48: {
              extraCase_ = 6;
              extra_ = input.readUInt32();
              break;
            }
            case 58: {
                String s = input.readStringRequireUtf8();

              swstatus_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EventOuterClass.internal_static_Event_descriptor;
    }

      public static Event parseFrom(
              com.google.protobuf.ByteString data)
              throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
      }

      public static Event parseFrom(
              com.google.protobuf.ByteString data,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
      }

      public static Event parseFrom(byte[] data)
              throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
      }

      public static Event parseFrom(
              byte[] data,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
      }

      public static Event parseFrom(java.io.InputStream input)
              throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
                  .parseWithIOException(PARSER, input);
      }

      public static Event parseFrom(
              java.io.InputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
                  .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static Event parseDelimitedFrom(java.io.InputStream input)
              throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
                  .parseDelimitedWithIOException(PARSER, input);
      }

      public static Event parseDelimitedFrom(
              java.io.InputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
                  .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }

      public static Event parseFrom(
              com.google.protobuf.CodedInputStream input)
              throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
                  .parseWithIOException(PARSER, input);
      }

      public static Event parseFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
                  .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static Builder newBuilder() {
          return DEFAULT_INSTANCE.toBuilder();
      }

      public static Builder newBuilder(Event prototype) {
          return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }

      public static Event getDefaultInstance() {
          return DEFAULT_INSTANCE;
      }

      public static com.google.protobuf.Parser<Event> parser() {
          return PARSER;
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
          return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }

      protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EventOuterClass.internal_static_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
                  Event.class, Builder.class);
    }

    public ExtraCase
    getExtraCase() {
      return ExtraCase.forNumber(
          extraCase_);
    }

    /**
     * <pre>
     * Timestamp
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp timestamp = 1;</code>
     */
    public boolean hasTimestamp() {
      return timestamp_ != null;
    }

    /**
     * <pre>
     * Timestamp
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp timestamp = 1;</code>
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
    }

    /**
     * <pre>
     * Timestamp
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp timestamp = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      return getTimestamp();
    }

    /**
     * <pre>
     * Hub serial number
     * </pre>
     *
     * <code>optional string serial = 2;</code>
     */
    public String getSerial() {
        Object ref = serial_;
        if (ref instanceof String) {
            return (String) ref;
      } else {
            com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
        serial_ = s;
        return s;
      }
    }

    /**
     * <pre>
     * Hub serial number
     * </pre>
     *
     * <code>optional string serial = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSerialBytes() {
        Object ref = serial_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
        serial_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <pre>
     * Child ID
     * </pre>
     *
     * <code>optional string child_id = 3;</code>
     */
    public String getChildId() {
        Object ref = childId_;
        if (ref instanceof String) {
            return (String) ref;
      } else {
            com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
        childId_ = s;
        return s;
      }
    }

    /**
     * <pre>
     * Child ID
     * </pre>
     *
     * <code>optional string child_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getChildIdBytes() {
        Object ref = childId_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
        childId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <pre>
     * Event type
     * </pre>
     *
     * <code>optional .EventType event = 4;</code>
     */
    public int getEventValue() {
      return event_;
    }

    /**
     * <pre>
     * Event type
     * </pre>
     *
     * <code>optional .EventType event = 4;</code>
     */
    public EventType getEvent() {
        EventType result = EventType.valueOf(event_);
        return result == null ? EventType.UNRECOGNIZED : result;
    }

    /**
     * <pre>
     * Heart rate in BPM
     * </pre>
     *
     * <code>optional uint32 heart_rate = 5;</code>
     */
    public int getHeartRate() {
      if (extraCase_ == 5) {
          return (Integer) extra_;
      }
      return 0;
    }

    /**
     * <pre>
     * Battery percentage
     * </pre>
     *
     * <code>optional uint32 battery_percentage = 6;</code>
     */
    public int getBatteryPercentage() {
      if (extraCase_ == 6) {
          return (Integer) extra_;
      }
      return 0;
    }

    /**
     * <code>optional string swstatus = 7;</code>
     */
    public String getSwstatus() {
        Object ref = swstatus_;
        if (ref instanceof String) {
            return (String) ref;
      } else {
            com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
        swstatus_ = s;
        return s;
      }
    }

    /**
     * <code>optional string swstatus = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSwstatusBytes() {
        Object ref = swstatus_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
        swstatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestamp_ != null) {
        output.writeMessage(1, getTimestamp());
      }
      if (!getSerialBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, serial_);
      }
      if (!getChildIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, childId_);
      }
        if (event_ != EventType.UNKNOWN.getNumber()) {
        output.writeEnum(4, event_);
      }
      if (extraCase_ == 5) {
        output.writeUInt32(
                5, (int) ((Integer) extra_));
      }
      if (extraCase_ == 6) {
        output.writeUInt32(
                6, (int) ((Integer) extra_));
      }
      if (!getSwstatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, swstatus_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestamp_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTimestamp());
      }
      if (!getSerialBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, serial_);
      }
      if (!getChildIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, childId_);
      }
        if (event_ != EventType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, event_);
      }
      if (extraCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(
                  5, (int) ((Integer) extra_));
      }
      if (extraCase_ == 6) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(
                  6, (int) ((Integer) extra_));
      }
      if (!getSwstatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, swstatus_);
      }
      memoizedSize = size;
      return size;
    }

      @Override
      public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
          if (!(obj instanceof Event)) {
        return super.equals(obj);
      }
          Event other = (Event) obj;

      boolean result = true;
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && getTimestamp()
            .equals(other.getTimestamp());
      }
      result = result && getSerial()
          .equals(other.getSerial());
      result = result && getChildId()
          .equals(other.getChildId());
      result = result && event_ == other.event_;
      result = result && getSwstatus()
          .equals(other.getSwstatus());
      result = result && getExtraCase().equals(
          other.getExtraCase());
      if (!result) return false;
      switch (extraCase_) {
        case 5:
          result = result && (getHeartRate()
              == other.getHeartRate());
          break;
        case 6:
          result = result && (getBatteryPercentage()
              == other.getBatteryPercentage());
          break;
        case 0:
        default:
      }
      return result;
    }

      @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
      }
      hash = (37 * hash) + SERIAL_FIELD_NUMBER;
      hash = (53 * hash) + getSerial().hashCode();
      hash = (37 * hash) + CHILD_ID_FIELD_NUMBER;
      hash = (53 * hash) + getChildId().hashCode();
      hash = (37 * hash) + EVENT_FIELD_NUMBER;
      hash = (53 * hash) + event_;
      hash = (37 * hash) + SWSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getSwstatus().hashCode();
      switch (extraCase_) {
        case 5:
          hash = (37 * hash) + HEART_RATE_FIELD_NUMBER;
          hash = (53 * hash) + getHeartRate();
          break;
        case 6:
          hash = (37 * hash) + BATTERY_PERCENTAGE_FIELD_NUMBER;
          hash = (53 * hash) + getBatteryPercentage();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public Builder newBuilderForType() { return newBuilder(); }

    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

      @Override
    protected Builder newBuilderForType(
              BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

      @Override
      public com.google.protobuf.Parser<Event> getParserForType() {
          return PARSER;
      }

      public Event getDefaultInstanceForType() {
          return DEFAULT_INSTANCE;
      }

      public enum ExtraCase
              implements com.google.protobuf.Internal.EnumLite {
          HEART_RATE(5),
          BATTERY_PERCENTAGE(6),
          EXTRA_NOT_SET(0);
          private final int value;

          private ExtraCase(int value) {
              this.value = value;
          }

          /**
           * @deprecated Use {@link #forNumber(int)} instead.
           */
          @Deprecated
          public static ExtraCase valueOf(int value) {
              return forNumber(value);
          }

          public static ExtraCase forNumber(int value) {
              switch (value) {
                  case 5:
                      return HEART_RATE;
                  case 6:
                      return BATTERY_PERCENTAGE;
                  case 0:
                      return EXTRA_NOT_SET;
                  default:
                      return null;
              }
          }

          public int getNumber() {
              return this.value;
          }
      }

    /**
     * <pre>
     * Event [device/hub/SN_HUB/events]
     *    Event report.
     * </pre>
     *
     * Protobuf type {@code Event}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Event)
            EventOrBuilder {
        private int extraCase_ = 0;
        private Object extra_;
        private com.google.protobuf.Timestamp timestamp_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
                com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
        private Object serial_ = "";
        private Object childId_ = "";
        private int event_ = 0;
        private Object swstatus_ = "";

      // Construct using EventOuterClass.Event.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return EventOuterClass.internal_static_Event_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return EventOuterClass.internal_static_Event_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Event.class, Builder.class);
        }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }

      public Builder clear() {
        super.clear();
        if (timestampBuilder_ == null) {
          timestamp_ = null;
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }
        serial_ = "";

        childId_ = "";

        event_ = 0;

        swstatus_ = "";

        extraCase_ = 0;
        extra_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EventOuterClass.internal_static_Event_descriptor;
      }

        public Event getDefaultInstanceForType() {
            return Event.getDefaultInstance();
        }

        public Event build() {
            Event result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
        }

        public Event buildPartial() {
            Event result = new Event(this);
        if (timestampBuilder_ == null) {
          result.timestamp_ = timestamp_;
        } else {
          result.timestamp_ = timestampBuilder_.build();
        }
        result.serial_ = serial_;
        result.childId_ = childId_;
        result.event_ = event_;
        if (extraCase_ == 5) {
          result.extra_ = extra_;
        }
        if (extraCase_ == 6) {
          result.extra_ = extra_;
        }
        result.swstatus_ = swstatus_;
        result.extraCase_ = extraCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }

      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }

      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }

      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }

      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }

      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Event) {
              return mergeFrom((Event)other);
        } else {
          super.mergeFrom(other);
          return this;
          }
      }

        public Builder mergeFrom(Event other) {
            if (other == Event.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          mergeTimestamp(other.getTimestamp());
        }
        if (!other.getSerial().isEmpty()) {
          serial_ = other.serial_;
          onChanged();
        }
        if (!other.getChildId().isEmpty()) {
          childId_ = other.childId_;
          onChanged();
        }
        if (other.event_ != 0) {
          setEventValue(other.getEventValue());
        }
        if (!other.getSwstatus().isEmpty()) {
          swstatus_ = other.swstatus_;
          onChanged();
        }
        switch (other.getExtraCase()) {
          case HEART_RATE: {
            setHeartRate(other.getHeartRate());
            break;
          }
          case BATTERY_PERCENTAGE: {
            setBatteryPercentage(other.getBatteryPercentage());
            break;
          }
          case EXTRA_NOT_SET: {
            break;
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
          Event parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Event) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      public ExtraCase
          getExtraCase() {
        return ExtraCase.forNumber(
            extraCase_);
      }

      public Builder clearExtra() {
        extraCase_ = 0;
        extra_ = null;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * Timestamp
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp timestamp = 1;</code>
       */
      public boolean hasTimestamp() {
        return timestampBuilder_ != null || timestamp_ != null;
      }

      /**
       * <pre>
       * Timestamp
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp timestamp = 1;</code>
       */
      public com.google.protobuf.Timestamp getTimestamp() {
        if (timestampBuilder_ == null) {
          return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        } else {
          return timestampBuilder_.getMessage();
        }
      }

      /**
       * <pre>
       * Timestamp
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp timestamp = 1;</code>
       */
      public Builder setTimestamp(
              com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timestampBuilder_ == null) {
            timestamp_ = builderForValue.build();
          onChanged();
        } else {
            timestampBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }

      /**
       * <pre>
       * Timestamp
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp timestamp = 1;</code>
       */
      public Builder setTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
            if (value == null) {
                throw new NullPointerException();
            }
            timestamp_ = value;
          onChanged();
        } else {
            timestampBuilder_.setMessage(value);
        }

        return this;
      }

      /**
       * <pre>
       * Timestamp
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp timestamp = 1;</code>
       */
      public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (timestamp_ != null) {
            timestamp_ =
              com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
          } else {
            timestamp_ = value;
          }
          onChanged();
        } else {
          timestampBuilder_.mergeFrom(value);
        }

        return this;
      }

      /**
       * <pre>
       * Timestamp
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        if (timestampBuilder_ == null) {
          timestamp_ = null;
          onChanged();
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }

        return this;
      }

      /**
       * <pre>
       * Timestamp
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp timestamp = 1;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {

        onChanged();
        return getTimestampFieldBuilder().getBuilder();
      }

      /**
       * <pre>
       * Timestamp
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp timestamp = 1;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
        if (timestampBuilder_ != null) {
          return timestampBuilder_.getMessageOrBuilder();
        } else {
          return timestamp_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        }
      }

      /**
       * <pre>
       * Timestamp
       * </pre>
       *
       * <code>optional .google.protobuf.Timestamp timestamp = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>
          getTimestampFieldBuilder() {
        if (timestampBuilder_ == null) {
          timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTimestamp(),
                  getParentForChildren(),
                  isClean());
          timestamp_ = null;
        }
        return timestampBuilder_;
      }

      /**
       * <pre>
       * Hub serial number
       * </pre>
       *
       * <code>optional string serial = 2;</code>
       */
      public String getSerial() {
          Object ref = serial_;
          if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
              String s = bs.toStringUtf8();
          serial_ = s;
          return s;
          } else {
              return (String) ref;
          }
      }

        /**
         * <pre>
         * Hub serial number
         * </pre>
         * <p>
         * <code>optional string serial = 2;</code>
         */
        public Builder setSerial(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            serial_ = value;
            onChanged();
            return this;
        }

      /**
       * <pre>
       * Hub serial number
       * </pre>
       *
       * <code>optional string serial = 2;</code>
       */
      public com.google.protobuf.ByteString
      getSerialBytes() {
          Object ref = serial_;
          if (ref instanceof String) {
              com.google.protobuf.ByteString b =
                      com.google.protobuf.ByteString.copyFromUtf8(
                              (String) ref);
          serial_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <pre>
       * Hub serial number
       * </pre>
       *
       * <code>optional string serial = 2;</code>
       */
      public Builder setSerialBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
            throw new NullPointerException();
        }
          checkByteStringIsUtf8(value);

        serial_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * Hub serial number
       * </pre>
       *
       * <code>optional string serial = 2;</code>
       */
      public Builder clearSerial() {

        serial_ = getDefaultInstance().getSerial();
        onChanged();
        return this;
      }

      /**
       * <pre>
       * Child ID
       * </pre>
       *
       * <code>optional string child_id = 3;</code>
       */
      public String getChildId() {
          Object ref = childId_;
          if (!(ref instanceof String)) {
              com.google.protobuf.ByteString bs =
                      (com.google.protobuf.ByteString) ref;
              String s = bs.toStringUtf8();
              childId_ = s;
              return s;
          } else {
              return (String) ref;
          }
      }

        /**
         * <pre>
         * Child ID
         * </pre>
         * <p>
         * <code>optional string child_id = 3;</code>
         */
        public Builder setChildId(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            childId_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Child ID
       * </pre>
       *
       * <code>optional string child_id = 3;</code>
         */
        public com.google.protobuf.ByteString
        getChildIdBytes() {
            Object ref = childId_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (String) ref);
          childId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
        }

      /**
       * <pre>
       * Child ID
       * </pre>
       *
       * <code>optional string child_id = 3;</code>
       */
      public Builder setChildIdBytes(
              com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
          }
          checkByteStringIsUtf8(value);

        childId_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * Child ID
       * </pre>
       *
       * <code>optional string child_id = 3;</code>
       */
      public Builder clearChildId() {

        childId_ = getDefaultInstance().getChildId();
        onChanged();
        return this;
      }

      /**
       * <pre>
       * Event type
       * </pre>
       *
       * <code>optional .EventType event = 4;</code>
       */
      public int getEventValue() {
        return event_;
      }

      /**
       * <pre>
       * Event type
       * </pre>
       *
       * <code>optional .EventType event = 4;</code>
       */
      public Builder setEventValue(int value) {
        event_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * Event type
       * </pre>
       *
       * <code>optional .EventType event = 4;</code>
       */
      public EventType getEvent() {
          EventType result = EventType.valueOf(event_);
          return result == null ? EventType.UNRECOGNIZED : result;
      }

      /**
       * <pre>
       * Event type
       * </pre>
       *
       * <code>optional .EventType event = 4;</code>
       */
      public Builder setEvent(EventType value) {
        if (value == null) {
          throw new NullPointerException();
        }

        event_ = value.getNumber();
        onChanged();
        return this;
      }

      /**
       * <pre>
       * Event type
       * </pre>
       *
       * <code>optional .EventType event = 4;</code>
       */
      public Builder clearEvent() {

        event_ = 0;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * Heart rate in BPM
       * </pre>
       *
       * <code>optional uint32 heart_rate = 5;</code>
       */
      public int getHeartRate() {
        if (extraCase_ == 5) {
            return (Integer) extra_;
        }
        return 0;
      }

      /**
       * <pre>
       * Heart rate in BPM
       * </pre>
       *
       * <code>optional uint32 heart_rate = 5;</code>
       */
      public Builder setHeartRate(int value) {
        extraCase_ = 5;
        extra_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * Heart rate in BPM
       * </pre>
       *
       * <code>optional uint32 heart_rate = 5;</code>
       */
      public Builder clearHeartRate() {
        if (extraCase_ == 5) {
          extraCase_ = 0;
          extra_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <pre>
       * Battery percentage
       * </pre>
       *
       * <code>optional uint32 battery_percentage = 6;</code>
       */
      public int getBatteryPercentage() {
        if (extraCase_ == 6) {
            return (Integer) extra_;
        }
        return 0;
      }

      /**
       * <pre>
       * Battery percentage
       * </pre>
       *
       * <code>optional uint32 battery_percentage = 6;</code>
       */
      public Builder setBatteryPercentage(int value) {
        extraCase_ = 6;
        extra_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * Battery percentage
       * </pre>
       *
       * <code>optional uint32 battery_percentage = 6;</code>
       */
      public Builder clearBatteryPercentage() {
        if (extraCase_ == 6) {
          extraCase_ = 0;
          extra_ = null;
          onChanged();
        }
        return this;
      }

        /**
         * <code>optional string swstatus = 7;</code>
         */
        public String getSwstatus() {
            Object ref = swstatus_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                swstatus_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>optional string swstatus = 7;</code>
         */
        public Builder setSwstatus(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            swstatus_ = value;
            onChanged();
            return this;
        }

        /**
       * <code>optional string swstatus = 7;</code>
         */
      public com.google.protobuf.ByteString
      getSwstatusBytes() {
          Object ref = swstatus_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (String) ref);
          swstatus_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

        /**
         * <code>optional string swstatus = 7;</code>
         */
        public Builder setSwstatusBytes(
                com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
        }
            checkByteStringIsUtf8(value);

        swstatus_ = value;
        onChanged();
        return this;
        }

      /**
       * <code>optional string swstatus = 7;</code>
       */
      public Builder clearSwstatus() {

        swstatus_ = getDefaultInstance().getSwstatus();
        onChanged();
        return this;
      }

      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Event)
    }

  }

  // @@protoc_insertion_point(outer_class_scope)
}
